image: zaguee/ngcli:0.0.1

# cache:
#   untracked: true
#   key: "$CI_BUILD_REF_NAME"
#   paths:
#     - node_modules/

stages:
  #- setup
  - lint
  - build
  
# setup:
#   stage: setup
#   script:
#     - npm install
#   cache:
#     paths:
#       - node_modules
 
lint:
  stage: lint
  script:
    - node --version
    - ng --version
    - ng lint
  # cache:
  #   paths:
  #     - node_modules
 
build:
  stage: build
  script:
    - node --version
    - ng --version
    - ng build --prod
  # cache:
  #   paths:
  #     - node_modules
  artifacts:
    paths:
      - dist