image: registry.segip.gob.bo/base/frontend-ci:1.0.1

stages:
  - tests
  - build
  - docker
  - docs

lint:
  stage: tests
  before_script:
  - tar -zxf /root/mods.tar.gz
  script:
    - ng lint

docs:
  stage: docs
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" https://registry.segip.gob.bo
  script:
    - npm run compodoc
    - docker build -t registry.segip.gob.bo/base/frontend:docs --build-arg ENV=docs .
    - docker push registry.segip.gob.bo/base/frontend:docs
  artifacts:
    name: "DOCS($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-docs

build-dev:
  stage: build
  before_script:
    - tar -zxf /root/mods.tar.gz
  script:
    - npm run build:dev
  artifacts:
    name: "DISTDEV($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-dev

build-anl:
  stage: build
  before_script:
    - tar -zxf /root/mods.tar.gz
  script:
    - npm run build:anl
  artifacts:
    name: "DISTANL($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-anl

build-test:
  stage: build
  before_script:
    - tar -zxf /root/mods.tar.gz
  script:
    - npm run build:test
  artifacts:
    name: "DISTTEST($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-test

docker-anl:
  stage: docker
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" https://registry.segip.gob.bo
  script:
    - docker build -t registry.segip.gob.bo/base/frontend:stable-analisis --build-arg ENV=anl .
    - docker push registry.segip.gob.bo/base/frontend:stable-analisis
  environment:
    name: svr-analisis
    url: http://base.analisis.local

docker-dev:
  stage: docker
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" https://registry.segip.gob.bo
  script:
    - docker build -t registry.segip.gob.bo/base/frontend:stable-dev --build-arg ENV=dev .
    - docker push registry.segip.gob.bo/base/frontend:stable-dev
  environment:
    name: svr-dev
    url: http://base.dev.local

docker-test:
  stage: docker
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" https://registry.segip.gob.bo
  script:
    - docker build -t registry.segip.gob.bo/base/frontend:stable-test --build-arg ENV=test .
    - docker push registry.segip.gob.bo/base/frontend:stable-test
  environment:
    name: svr-test
    url: http://base.test.local
