image: registry.segip.gob.bo/base/frontend-ci:1.0.1

before_script:
  - tar -zxf /root/mods.tar.gz

stages:
  #- docs
  #- tests
  - build
  #- deploy

# docs:
#   stage: docs
#   script:
#     - npm run compodoc
#   artifacts:
#     name: "DOCS($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
#     paths:
#       - docs
# lint:
#   stage: tests
#   script:
#     - ng lint

build-dev:
  stage: build
  script:
    - npm run build:dev
  artifacts:
    name: "DISTDEV($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-dev

build-anl:
  stage: build
  script:
    - npm run build:anl
  artifacts:
    name: "DISTANL($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-anl

build-test:
  stage: build
  script:
    - npm run build:test
  artifacts:
    name: "DISTTEST($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-test
# deploy:
#   stage: deploy
#   script:
#     - docker info
#     - docker build -t registry.segip.gob.bo/base/frontend:stable .
