image: zaguee/ngcli:6.0.3

# cache:
#   untracked: true
#   key: "$CI_BUILD_REF_NAME"
#   paths:
#     - node_modules/

stages:
  - setup
  - lint
  - build
  
setup:
  stage: setup
  script:
    - npm install
  artifacts:
    paths:
      - dist
  cache:
    paths:
      - node_modules
 
lint:
  stage: lint
  script:
    - node --version
    #- ng --version
    - ng lint

build:
  stage: build
  script:
    - node --version
    #- ng --version
    - ng build --prod
  artifacts:
    paths:
      - dist