image: zaguee/base9

before_script:
  - tar -zxf /root/dev/mods.tar.gz

stages:
  - docs
  - tests
  - build
  
docs:
  stage: docs
  script:
    - npm run compodoc
  artifacts:
    paths:
      - docs
lint:
  stage: tests
  script:
    - ng lint

build:
  stage: build
  script:
    - ng build --prod --no-progress
  artifacts:
    paths:
      - dist
