image: registry.segip.gob.bo/base/frontend-ci:1.0.1

before_script:
  - tar -zxf /root/mods.tar.gz

stages:
  - tests
  - build
  - docker
  - docs

lint:
  stage: tests
  script:
    - ng lint

compodoc:
  stage: docs
  script:
    - npm run compodoc
    - docker build -t registry.segip.gob.bo/base/frontend:docs --build-arg ENV=docs .
    - docker push registry.segip.gob.bo/base/frontend:docs
  artifacts:
    name: "DOCS($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - docs

build-dev:
  stage: build
  script:
    - npm run build:dev
  artifacts:
    name: "DISTDEV($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-dev

build-anl:
  stage: build
  script:
    - npm run build:anl
  artifacts:
    name: "DISTANL($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-anl

build-test:
  stage: build
  script:
    - npm run build:test
  artifacts:
    name: "DISTTEST($CI_COMMIT_REF_NAME-$CI_COMMIT_SHA)"
    paths:
      - dist-test

docker-anl:
  stage: docker
  script:
    - docker build -t registry.segip.gob.bo/base/frontend:stable-analisis --build-arg ENV=anl .
    - docker push registry.segip.gob.bo/base/frontend:stable-analisis

docker-dev:
  stage: docker
  script:
    - docker build -t registry.segip.gob.bo/base/frontend:stable-dev --build-arg ENV=dev .
    - docker push registry.segip.gob.bo/base/frontend:stable-dev

docker-test:
  stage: docker
  script:
    - docker build -t registry.segip.gob.bo/base/frontend:stable-test --build-arg ENV=test .
    - docker push registry.segip.gob.bo/base/frontend:stable-test
