image: zaguee/base:0.0.1


stages:
  - ci
  
ci:
  stage: ci
  script:
    - npm install
    - ng lint
    - ng build --prod --no-progress
  artifacts:
    paths:
      - dist

# stages:
#   - setup
#   - lint
#   - build
  
# setup:
#   stage: setup
#   script:
#     - npm ci
 
# lint:
#   stage: lint
#   script:
#     - node --version
#     - ng lint
 
# build:
#   stage: build
#   script:
#     - node --version
#     - ng build --prod
#   artifacts:
#     paths:
#       - dist