image: zaguee/ngcli:6.0.3

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - setup
  - lint
  - build
  
setup:
  stage: setup
  script:
    - node --version
    - ng --version
    - rm -rf node-modules
    - npm install
 
lint:
  stage: lint
  script:
    - ng lint

build:
  stage: build
  script:
    - ng build --prod
  artifacts:
    paths:
      - dist